name: homecoffe
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  logger: ^2.4.0
  auto_size_text: ^3.0.0
  persistent_bottom_nav_bar: any
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/icons/185112_coffee_espresso_barista_icon.svg
      - assets/icons/2672723_coffee_app_object_bean_essential_icon.svg
      - assets/icons/5404318_coffee_cup_glass_hot_icon.svg
      - assets/icons/9035990_person_circle_sharp_icon.svg
      - assets/icons/3098737_coffee_machine2.svg
      - assets/icons/216411_star_icon.svg
      - assets/icons/889377_italian_coffee_machine.svg
      - assets/icons/211817_search_strong_icon.svg

  fonts:
    - family: Caramel
      fonts:
        - asset: fonts/Super_Caramel.ttf
          style: normal